name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  $CHANGES

# Label definitions
sort-by: 'merged_at'
sort-direction: 'descending'
exclude-labels:
  - 'changelog/exclude'

# Category definitions
category-template: '## $TITLE'
categories:
  - title: '🚨 Breaking Changes'
    labels:
      - 'breaking-change'
  - title: '🏢 Business'
    labels:
      - 'business'
  - title: '🏗️ Internal'
    labels:
      - 'internal'
  - title: '🛠 Technical Debt'
    labels:
      - 'technical-debt'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📦️ Dependencies'
    labels:
      - 'dependencies'

# Change definitions
no-changes-template: '* No changes'
change-template: '* [#$NUMBER] $TITLE - @$AUTHOR'
change-title-escapes: '\<*_&'

# Versioning definitions
version-resolver:
  major:
    labels:
      - 'release/major'
      - 'breaking-change'
  minor:
    labels:
      - 'release/minor'
      - 'internal'
  patch:
    labels:
      - 'release/patch'
      - 'bug'
  default: 'minor'

include-pre-releases: true
filter-by-commitish: true
commitish: master
