name: 'renovate-auto-approve-action'
description: 'Detect and automatically approve renovate PRs'
author: 'lucaslim'
inputs:
  token:
    required: true
    description: 'GitHub or GitHub app token'

runs:
  using: 'node20'
  main: 'dist/index.js'
